define: &radius 0.65   #0.35 for arov, 0.65 for asv
define: &base_frame "/asv/base_link"
define: &model "DiffDrive" # "Omni" for arov, "DiffDrive" for asv
define: &goal_cost 3.0  # 8.0 for arov, 3.0 for asv, 5.0 default
define: &goal_thresh 1  # 2m for arov, 1m for asv
#define: &path_thresh 1  # 1m for arov, 0.5m for asv
define: &path_mode 0  # 1 for arov, 0 for asv

global_costmap:
  global_costmap:
    ros__parameters:
      global_frame: map
      robot_base_frame: *base_frame
      robot_radius: *radius
      resolution: 0.01
      update_frequency: 5.0
      publish_frequency: 5.0
      track_unknown_space: False
      use_sim_time: False
      rolling_window: False

      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: True
        footprint_clearing_enabled: True
        restore_cleared_footprint: True
        map_subscribe_transient_local: True
        transform_tolerance: 0.0
        map_topic: map
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.3
        cost_scaling_factor: 3.0
      always_send_full_costmap: True

local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: odom
      robot_base_frame: *base_frame
      robot_radius: *radius
      height: 3
      width: 3
      resolution: 0.01
      publish_frequency: 5.0
      update_frequency: 5.0
      use_sim_time: False
      rolling_window: True

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    publish_zero_velocity: True
    costmap_update_timeout: 0.6 # after 3 failed updates timeout
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3      # after fails for 0.3s then fail pathing action

    controller_plugins: [ "FollowPath" ]
    progress_checker_plugins: [ "progress_checker" ]
    goal_checker_plugins: [ "SimpleGoalChecker" ]
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      motion_model: *model
      time_steps: 20
      model_dt: 0.1
      batch_size: 2000
      iteration_count: 1
      temperature: 0.3
      gamma: 0.015
      prune_distance: 1.5 # default value
      vx_std: 0.2
      vx_min: 0.1
      vx_max: 0.5
      ax_min: -2.0
      ax_max: 2.0
      vy_std: 0.2
      vy_max: 0.5
      ay_min: -2.0
      ay_max: 2.0
      wz_std: 0.2
      wz_max: 1.0
      az_max: 2.0
      ConstraintCritic:
        enabled: True
        cost_power: 1
        cost_weight: 4.0
      CostCritic:
        enabled: True
        cost_power: 1
        cost_weight: 3.81
        critical_cost: 300.0
        consider_footprint: True
        collision_cost: 1000000.0
        near_goal_distance: 1.0
        trajectory_point_step: 2
      GoalCritic:
        enabled: True
        cost_power: 1
        cost_weight: *goal_cost  # higher - closer to goal, lower - more lax, default 5.0
        threshold_to_consider: *goal_thresh  # time_steps * model_dt
      GoalAngleCritic:
        enabled: True
        cost_power: 1
        cost_weight: *goal_cost  # higher - closer to goal, lower - more lax, default 3.0
        threshold_to_consider: 1  # start rotating to goal pose 1m away
      PathAlignCritic:
        enabled: True
        cost_power: 1
        cost_weight: 14.0
        threshold_to_consider: *goal_thresh
      PathAngleCritic:
        enabled: True
        cost_power: 1
        cost_weight: 2.0
        threshold_to_consider: *goal_thresh
        mode: *path_mode
      PathFollowCritic:
        enabled: True
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: *goal_thresh
      PreferForwardCritic:
        enabled: True
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: *goal_thresh
#      TwirlingCritic: # disable on ASV, makes sure AROV doesn't spin in place
#        enabled: True
#        twirling_cost_power: 1
#        twirling_cost_weight: 10.0

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 5

    SimpleGoalChecker:
      xy_goal_tolerance: 0.1
      yaw_goal_tolerance: 0.1
      stateful: True
