define: &radius 0.35   #0.35 for arov, 0.65 for asv
define: &base_frame "arov/base_link"

global_costmap:
  global_costmap:
    ros__parameters:
      global_frame: map
      robot_base_frame: *base_frame
      robot_radius: *radius
      resolution: 0.01
      update_frequency: 5.0
      publish_frequency: 5.0
      track_unknown_space: False
      use_sim_time: False
      rolling_window: False

      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: True
        footprint_clearing_enabled: True
        restore_cleared_footprint: True
        map_subscribe_transient_local: True
        transform_tolerance: 0.0
        map_topic: map
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.3
        cost_scaling_factor: 3.0
      always_send_full_costmap: True

local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: odom
      robot_base_frame: *base_frame
      robot_radius: *radius
      height: 3
      width: 3
      resolution: 0.01
      publish_frequency: 5.0
      update_frequency: 5.0
      use_sim_time: False
      rolling_window: True