control_action_server:
  ros__parameters:
    # TODO: convert to meters
    cleaning_routine_depth: 6.0
    cleaning_routine_width: 8.0
    cleaning_routine_strip_width: 1.0
    cleaning_routine_apriltag_offset: 0.0
    cleaning_routine_apriltag_clearance: 0.0